server:
  port: 3006
spring:
  application:
    name: xc‐service‐consumer
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 6MB
      max-request-size: 100MB
img:
  imgUrl: http://192.168.5.233:8888/
fastdfs:
  connect_timeout_in_seconds: 5
  network_timeout_in_seconds: 30
  charset: UTF-8
  http_anti_steal_token: false
  http_secret_key: FastDFS1234567890
  http_tracker_http_port: 80
  tracker_servers: 192.168.5.233:22122